Repository gogaille/blog, pull requests merged in 2021-04, with the labels that each got.

#52 feature: Use NextMDX to load blog post
  content/author/shouze.mdx
  content/author/timbarray.mdx
  content/posts/how-redefining-software-quality-can-save-your-day.mdx
  content/posts/intro.mdx
  next-mdx.json
  package.json
  pages/index.tsx
  pages/posts/[...slug].tsx
  src/@types/remark-html.d.ts
  src/@types/remark-remark-highlight.d.ts
  src/api.ts
  src/components/hero-post.tsx
  src/components/more-stories.tsx
  src/components/post-body.tsx
  src/components/post-header.tsx
  src/components/post-preview.tsx
  src/domain/author.ts
  src/domain/post.ts
  src/feed.ts
  src/markdown.ts
  src/types.ts
  yarn.lock
Labels: enhancement

#62 fix: add more space between the footer button on mobile
  src/components/footer.tsx
Labels: bug

#65 chore: Setup CI
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yaml
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/posts/[...slug].tsx
  src/components/alert.tsx
  src/components/author.tsx
  src/components/blog-image.tsx
  src/components/container.tsx
  src/components/cover-image.tsx
  src/components/date-formatter.tsx
  src/components/footer.tsx
  src/components/header.tsx
  src/components/hero-post.tsx
  src/components/intro.tsx
  src/components/layout.tsx
  src/components/meta.tsx
  src/components/more-stories.tsx
  src/components/post-header.tsx
  src/components/post-preview.tsx
  src/components/post-title.tsx
  src/components/reading-time.tsx
  src/components/section-separator.tsx
  src/components/utterances.tsx
  src/feed.ts
  src/types.ts
  yarn.lock
Labels: enhancement

#68 fix: Fix canonical url on production #46
  .env.production
  next.config.js
  pages/_app.tsx
Labels: bug

#70 Harmonize last name case
  content/author/shouze.mdx
Labels: enhancement

#69 chore: upgrade dependencies
  next.config.js
  package.json
  yarn.lock
Labels: dependencies

#72 fix: remove unneeded bold font
  src/components/more-stories.tsx
Labels: bug

#71 feature: Preload fonts
  pages/_app.tsx
  src/styles/font.css
  tailwind.config.js
Labels: enhancement
